name: xibo_screen_example
copy_from: 
  provider: nextcloud
  path: path/to/your/nextcloud/folder
  auth: 
    type: basic_auth
    user: username
    password: your_password
  server: http://your-nextcloud-server.com
  extensions: 
    - .jpg
    - .png
    - .mp4
    - .avi
    - .pdf
  poll_interval: 10  # seconds
project_to:
  provider: xibo
  host: http://your-xibo-server.com/api/
  auth:
    type: oauth2
    grant_type: client_credentials
    client_id: your_client_id
    client_secret: your_client_secret
  display:
    name: Display Name
    width: 1920
    height: 1080
    background:
      color: '#000000'
